name: Go package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install alsa
        run: sudo apt-get install -y libasound2-dev

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.20.3

      - name: Build
        run: go build -v ./cmd/zekventsar/main.go

      - name: Test
        run: go test -v ./cmd/zekventsar/main.go