name: Go package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Get dependencies
        run: sudo apt-get update && sudo apt-get install -y gcc libgl1-mesa-dev libegl1-mesa-dev libgles2-mesa-dev libx11-dev xorg-dev libwayland-dev libxkbcommon-dev bc libasound2-dev
        if: ${{ runner.os == 'Linux' }}

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.20.3

      - name: Build
        run: go build -v ./cmd/zekventsar/main.go

      - name: Test
        run: go test -v ./cmd/zekventsar/main.go